DROP TABLE capitan CASCADE;
DROP TABLE cargo_ship CASCADE;
DROP TABLE cargo_type CASCADE;
/*DROP TABLE client CASCADE;*/
DROP TABLE fact_of_ticket_purchase CASCADE;
DROP TABLE intermediate_seaport_of_route CASCADE;
DROP TABLE passenger_ship CASCADE;
DROP TABLE passenger_ship_capacity CASCADE;
DROP TABLE route CASCADE;
DROP TABLE ship CASCADE;
DROP TABLE seaport CASCADE;
DROP TABLE stateroom_class CASCADE;
DROP TABLE ship_assigned_to_voyage CASCADE;
DROP TABLE ship_declaration CASCADE;
DROP TABLE ship_decommissioning_act CASCADE;
DROP TABLE ticket CASCADE;
DROP TABLE voyage CASCADE;
DROP TYPE class_name_enum;
DROP TYPE ship_class_enum;
DROP TYPE ship_type_enum;
DROP TYPE status_enum;